'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {ActivityService,ActivityFileStore,validate}=require('../src/activity.cjs');
const A={name:'Synthetic Editor',bundleId:'test.editor',path:'/do-not-save',title:'never-save'},B={name:'Synthetic Browser',bundleId:'test.browser'};
const settle=()=>new Promise(r=>setImmediate(r));
function fixture(saved={schema:1,segments:[]},provider){let mono=0,wall=100000,calls=0,writes=0,timer,stored=structuredClone(saved);const service=new ActivityService({store:{read:()=>structuredClone(stored),write:s=>{stored=structuredClone(s);writes++;}},foreground:async()=>{calls++;return provider?provider():A;},now:()=>mono,wall:()=>wall,setIntervalFn:f=>{timer=f;return 7;},clearIntervalFn:()=>{timer=null;}});return {service,advance(ms){mono+=ms;wall+=ms;},observe(app){return service.observe(app,mono,wall);},trigger:()=>timer?.(),get calls(){return calls;},get writes(){return writes;},get stored(){return stored;}};}
test('Default off makes no queries/writes;start idempotent,stop immediately prevents polling and late observations',async()=>{const f=fixture();await settle();assert.equal(f.calls,0);assert.equal(f.writes,0);assert.equal(f.service.snapshot().enabled,false);f.service.start();f.service.start();await settle();assert.equal(f.calls,1);f.advance(1000);f.observe(A);f.advance(500);f.service.stop();assert.equal(f.service.snapshot().apps[0].durationMs,1500);const stopped=f.stored;f.advance(10000);f.trigger();f.observe(B);await settle();assert.deepEqual(f.stored,stopped);assert.equal(f.calls,1);f.service.close();});
test('Duplicate/out-of-order samples and APP switches account each elapsed interval once;category stays user-confirmed',async()=>{const f=fixture();f.service.start();await settle();f.advance(1000);f.observe(A);f.observe(B);assert.equal(f.service.snapshot().segments.length,1);assert.equal(f.service.observe(B,-1,99999),false);f.advance(2000);f.observe(B);f.advance(3000);f.observe(B);const before=f.service.snapshot();assert.deepEqual(before.apps.map(a=>a.durationMs).sort(),[3000,3000]);assert.equal(before.segments.length,2);assert.equal(before.segments[0].category,'unknown');f.service.classify(before.segments[0].id,'writing');f.advance(500);f.observe(B);f.service.stop();const s=f.service.snapshot();assert.equal(s.apps.reduce((n,a)=>n+a.durationMs,0),6500);assert.equal(s.segments[0].categoryConfirmed,true);assert.deepEqual(Object.keys(s.segments[0].app).sort(),['bundleId','name']);assert.ok(!JSON.stringify(f.stored).includes('do-not-save'));assert.ok(!JSON.stringify(f.stored).includes('never-save'));f.service.close();});
test('Stop/restart resumes as a new unknown segment with zero offline credit and no automatic provider call',async()=>{const f=fixture();f.service.start();await settle();f.advance(1200);f.observe(A);f.service.stop();const saved=f.stored;f.advance(86400000);const reopened=fixture(saved);await settle();assert.equal(reopened.calls,0);assert.equal(reopened.service.snapshot().enabled,false);assert.equal(reopened.service.snapshot().apps[0].durationMs,1200);reopened.service.start();await settle();assert.equal(reopened.service.snapshot().segments.length,2);reopened.advance(200);reopened.observe(A);reopened.service.stop();assert.equal(reopened.service.snapshot().apps[0].durationMs,1400);reopened.service.close();f.service.close();});
test('Unknown APP remains unclassified;long gaps or clock discontinuities stop without rewarding or crediting gap',async()=>{const f=fixture();f.service.start();await settle();f.advance(500);f.observe(null);assert.equal(f.service.snapshot().segments.at(-1).app.name,'未知 APP');assert.equal(f.service.snapshot().segments.at(-1).category,'unknown');f.advance(20000);f.observe(B);assert.equal(f.service.snapshot().enabled,false);assert.equal(f.service.snapshot().apps.reduce((n,a)=>n+a.durationMs,0),500);const jump=fixture();jump.service.start();await settle();assert.equal(jump.service.observe(A,1000,900000),false);assert.equal(jump.service.snapshot().enabled,false);assert.equal(jump.service.snapshot().apps[0].durationMs,0);jump.service.close();f.service.close();});
test('Stopped pending read cannot write old APP after a restart;queries never overlap',async()=>{let resolve;const f=fixture(undefined,()=>new Promise(r=>{resolve=r;}));f.service.start();f.trigger();assert.equal(f.calls,1);f.service.stop();f.service.start();assert.equal(f.calls,1);resolve(B);await settle();assert.equal(f.service.snapshot().segments.length,0);f.trigger();assert.equal(f.calls,2);f.service.stop();resolve(A);await settle();assert.equal(f.service.snapshot().segments.length,0);f.service.close();});
test('Storage failures stop queries and corrupt history remains untouched',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'owl-activity-synthetic-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const store=new ActivityFileStore(dir);fs.writeFileSync(store.file,'broken');let calls=0;const service=new ActivityService({store,foreground:async()=>{calls++;return A;}});assert.ok(service.snapshot().fault);assert.throws(()=>service.start());assert.equal(calls,0);assert.equal(fs.readFileSync(store.file,'utf8'),'broken');service.close();const bad=new ActivityService({store:{read:()=>({schema:1,segments:[]}),write(){throw Error('synthetic full disk');}},foreground:async()=>A});bad.start();await settle();assert.equal(bad.snapshot().enabled,false);assert.ok(bad.snapshot().fault);bad.close();});
test('Real local file round-trip preserves synthetic APP aggregate and category;does not persist enabled state',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'owl-activity-roundtrip-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));let mono=0;const store=new ActivityFileStore(dir),s=new ActivityService({store,foreground:async()=>B,now:()=>mono,wall:()=>100000+mono});s.start();await settle();mono=2500;s.observe(B);s.classify(s.snapshot().activeId,'chatgpt-learning');s.stop();s.close();const saved=store.read();validate(saved);assert.equal(saved.segments[0].durationMs,2500);assert.equal(saved.segments[0].category,'chatgpt-learning');assert.ok(!('enabled'in saved));const reopen=new ActivityService({store,foreground:()=>{throw Error('Must not query automatically');}});assert.equal(reopen.snapshot().enabled,false);assert.equal(reopen.snapshot().apps[0].durationMs,2500);reopen.close();});
