'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process'),{once}=require('node:events');
test('Portable real-service HTTP path: APP-only UI, default off, synthetic classify, pause/restart and no legacy history',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'owl-cloud-synthetic-'));let child;const start=async()=>{
  child=spawn(process.execPath,[path.resolve(__dirname,'../scripts/cloud-preview.cjs')],{env:{...process.env,PORT:'0',OWL_CLOUD_TEST_DIR:dir},stdio:['ignore','pipe','pipe']});let errors='';child.stderr.on('data',s=>errors+=s);const exit=once(child,'exit');
  const ready=new Promise((resolve,reject)=>{let bytes='';child.stdout.on('data',b=>{bytes+=b;const line=bytes.split('\n')[0];try{resolve(JSON.parse(line));}catch{}});child.once('exit',()=>reject(Error(errors||'Server exited')));});const receipt=await ready;return {origin:new URL(receipt.url).origin,exit};
 };
 t.after(async()=>{if(child&&child.exitCode===null){child.kill('SIGTERM');await once(child,'exit');}fs.rmSync(dir,{recursive:true,force:true});});
 let run=await start();const get=async route=>(await fetch(run.origin+route)).json(),post=async(route,v)=>{const res=await fetch(run.origin+route,{method:'POST',headers:{origin:run.origin,'content-type':'application/json'},body:JSON.stringify(v)});assert.equal(res.status,200);return res.json();};
 const html=await(await fetch(run.origin+'/?mode=widget')).text();assert.ok(html.includes('cloud-bridge.js'));assert.equal(/focus-records-tab|id="history"|专注计时记录/.test(html),false);assert.ok(html.includes('id="app-records"'));assert.equal((await get('/test/activity-snapshot')).enabled,false);
 assert.equal((await fetch(run.origin+'/test/activity-command',{method:'POST',body:'{"type":"start"}'})).status,403);
 let s=await post('/test/command',{type:'start',requestId:'start',task:'Synthetic cloud timer',seconds:2});assert.equal(s.ok,true);s=await post('/test/advance',{ms:2000});assert.equal(s.focus.lastOutcome.outcome,'completed');assert.equal('records' in s.focus,false);assert.equal(s.focus.creditedMinutes,0);
 s=await post('/test/command',{type:'start',requestId:'next',task:'Synthetic recovery',seconds:60});const id=s.state.active.id;await post('/test/advance',{ms:1000});s=await post('/test/command',{type:'pause',sessionId:id,requestId:'pause'});const credit=s.state.totalFocusMs;
 await post('/test/activity-command',{type:'start'});await new Promise(r=>setTimeout(r,20));await post('/test/advance',{ms:3000});await post('/test/synthetic-app',{app:'browser'});await post('/test/advance',{ms:2000});let a=await get('/test/activity-snapshot');assert.equal(a.apps.length,2);assert.ok(a.apps.every(v=>v.app.name.startsWith('合成示例')));await post('/test/activity-command',{type:'classify',id:a.segments[0].id,category:'writing'});a=await post('/test/activity-command',{type:'stop'});assert.equal(a.enabled,false);assert.equal(a.segments[0].category,'writing');const saved=a.segments;await post('/test/advance',{ms:1000});assert.deepEqual((await get('/test/activity-snapshot')).segments,saved);assert.equal((await get('/test/snapshot')).totalFocusMs,credit);
 child.kill('SIGTERM');await run.exit;run=await start();s=await get('/test/snapshot');assert.equal(s.active.id,id);assert.equal(s.active.status,'paused');assert.equal(s.totalFocusMs,credit);assert.equal('records' in s,false);a=await get('/test/activity-snapshot');assert.equal(a.enabled,false);assert.deepEqual(a.segments,saved);assert.equal(a.segments[0].category,'writing');
 child.kill('SIGTERM');await run.exit;child=undefined;
});
