'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {CATALOG,DEFAULTS}=require('../src/collection.cjs'),rules=require('../ui/placement-rules.cjs'),{initialState,command}=require('../src/core.cjs'),{FileStore}=require('../src/store.cjs');
const state=()=>{const s=initialState();command(s,{type:'test-access',enabled:true,requestId:'on'},0);s.collectionCatalog=CATALOG;return s;};
test('schema7 exact backup and schema8 reopen preserve all original transforms/layers/rights with implicit original size',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'owl-size8-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const old=initialState();old.schema=7;old.testAccess={enabled:true,equipment:{...DEFAULTS,room:'stool','wall-art':'wall-owl-mona'},positions:{'wall-owl-mona':{x:-200,y:30,size:[190,237.5]}},layerOrder:[...old.layerOrder]};const bytes=Buffer.from(JSON.stringify(old,null,2)),file=path.join(dir,'focus-state.json');fs.writeFileSync(file,bytes);let store=new FileStore(dir);const s=store.read();assert.equal(s.schema,9);assert.deepEqual({...s,schema:7},old);const backup=path.join(dir,'focus-state.schema7-'+crypto.createHash('sha256').update(bytes).digest('hex')+'.json');assert(fs.readFileSync(backup).equals(bytes));store.close();store=new FileStore(dir);assert.deepEqual(store.read(),s);store.close();});
test('large original PNG lamps/rugs/plants and registered decorations resize around original anchor with exact aspect and bounds',()=>{for(const id of ['lamp-linen','rug-cream','plant-leaf','wall-owl-mona','floor-light-small','foreground-plant-small','pendant-small','floor-light-handheld','corner-vine-right','corner-curtain-right','flower-string-lights']){const item=CATALOG.items.find(i=>i.id===id),e={...DEFAULTS,[item.category]:id},p={},before=rules.bindings(CATALOG,e,p).find(r=>r.id===id);for(const factor of [.5,1.8]){const next=rules.resizeItem(CATALOG,e,p,id,factor),after=rules.bindings(CATALOG,e,next).find(r=>r.id===id);assert.deepEqual(after.offset,before.offset,id);assert(Math.abs(rules.sizeInfo(CATALOG,e,next,id).factor-factor)<1e-8);assert(Math.abs(after.worldBounds[2]/before.worldBounds[2]-factor)<1e-8,id);assert(Math.abs(after.worldBounds[3]/before.worldBounds[3]-factor)<1e-8,id);if(item.scene.placement)assert.deepEqual(after.scene.placement.position,before.scene.placement.position);else assert.deepEqual(after.scene.display.anchor,item.scene.display?.anchor||item.scene.contacts[0]);}}});
test('proportional table and attached prop keep surface anchor and relative placement; boundary refusal changes nothing',()=>{const e={...DEFAULTS,'side-furniture':'side-table',tabletop:'tabletop-books'},p={'side-table--tabletop-books':{x:4,y:0,size:[90,90]}},before=structuredClone(p),next=rules.resizeItem(CATALOG,e,p,'side-table',1.5),rows=rules.bindings(CATALOG,e,next),table=rows.find(r=>r.id==='side-table'),child=rows.find(r=>r.id==='tabletop-books');assert.deepEqual(child.scene.placement.position,table.scene.tabletopAnchor);assert.equal(next[child.key].x,6);assert.deepEqual(child.scene.placement.displaySize,[135,135]);assert.deepEqual(p,before);const tableWide=rules.resizeItem(CATALOG,e,{},'side-table',1.5),max=rules.resizeItem(CATALOG,e,tableWide,'tabletop-books',5),copy=structuredClone(max);assert.throws(()=>rules.resizeItem(CATALOG,e,max,'side-table',1.6),/摆件已到大小边界/);assert.deepEqual(max,copy);});
test('size, positions and layers stay atomic and stale-protected; cancellation leaves normal state untouched',async()=>{const {CollectionDraft}=await import('../ui/collection-draft.mjs'),s=state();s.testAccess.equipment.lamp='lamp-linen';const original=structuredClone(s),d=new CollectionDraft();d.begin(s);d.resize('lamp-linen',1.5);d.move('lamp-linen',{x:70,y:-20});d.moveLayer('lamp-linen',1);assert.deepEqual(s,original);const c={type:'room-set',requestId:'whole-scaled',...d.command()};command(s,c,0);assert.equal(rules.sizeInfo(CATALOG,s.testAccess.equipment,s.testAccess.positions,'lamp-linen').factor,1.5);assert.deepEqual(s.positions,original.positions);assert.deepEqual(s.layerOrder,original.layerOrder);assert.deepEqual(s.equipment,original.equipment);assert.equal(s.totalFocusMs,original.totalFocusMs);const saved=structuredClone(s);assert.throws(()=>command(s,{...c,requestId:'stale-sized'},0),/其他入口/);assert.deepEqual(s,saved);d.begin(s);d.resize('lamp-linen',.5);d.clear();assert.deepEqual(s,saved);});
test('chair/role stays fixed; real compositor scales original lamp and mirror while retaining registered anchor and room order',async()=>{const e={...DEFAULTS,lamp:'lamp-linen','corner-vine-right':'corner-vine-right'},p=rules.resizeItem(CATALOG,e,{},'lamp-linen',1.5),next=rules.resizeItem(CATALOG,e,p,'corner-vine-right',1.8);assert.throws(()=>rules.resizeItem(CATALOG,e,next,'stool',.5),/坐姿原比例/);const {composeRoom}=await import('../ui/room-assets.mjs'),{canvasFixture}=require('./helpers/canvas.cjs'),f=canvasFixture(),items={};for(const id of ['lamp-linen','corner-vine-right']){const s=CATALOG.items.find(i=>i.id===id).scene;items[id]={image:{tag:id},placement:s.placement,sourceSize:s.size,display:s.display};}composeRoom(f.canvas.getContext('2d'),{tag:'base'},items,e,{tag:'role'},{catalog:CATALOG,positions:next});const lamp=f.rootDraws.find(d=>d.image==='lamp-linen'),vine=f.rootDraws.find(d=>d.image==='corner-vine-right');assert.equal(lamp.matrix[0],1.5);assert.equal(lamp.matrix[3],1.5);assert.equal(vine.matrix[0],-1);assert.equal(vine.args[2],235*1.8);assert.equal(vine.args[3],352.5*1.8);assert(f.rootDraws.some(d=>d.image==='role'));});
test('new same-slot variant inherits size percentage rather than incompatible raw PNG dimensions',async()=>{const {CollectionDraft}=await import('../ui/collection-draft.mjs'),s=state();s.testAccess.equipment.lamp='lamp-linen';const d=new CollectionDraft();d.begin(s);d.resize('lamp-linen',1.4);d.choose('lamp','lamp-paper-oval');assert(Math.abs(rules.sizeInfo(CATALOG,d.equipment,d.positions,'lamp-paper-oval').factor-1.4)<1e-8);});

test('corrupt old schema7 unsupported legacy PNG size cannot become a successful migration',()=>{const s=state();s.schema=7;s.testAccess.equipment.lamp='lamp-linen';s.testAccess.positions['lamp-linen']={x:0,y:0,size:[1024,1536]};assert.throws(()=>require('../src/core.cjs').migrateState(s),/旧版本/);});
