'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {initialState,command,validateState,migrateState}=require('../src/core.cjs'),{FileStore}=require('../src/store.cjs'),{FocusService}=require('../src/service.cjs'),{SLOTS,LEGACY_SLOTS,displayEquipment}=require('../src/collection.cjs'),catalog=require('./fixtures/placement-catalog.cjs');
const outfit=s=>Object.fromEntries(SLOTS.map(k=>[k,displayEquipment(s)[k]]));
const room=(s,equipment,positions,id='room-save')=>({type:'room-set',requestId:id,equipment:{...outfit(s),...equipment},expectedEquipment:outfit(s),positions,expectedPositions:structuredClone(s.testAccess?.enabled?s.testAccess.positions:s.positions),expectedTestEnabled:Boolean(s.testAccess?.enabled)});
function oldState(){const s=initialState();s.totalFocusMs=s.settledFocusMs=600000;s.creditedMinutes=10;s.collection.owned=s.unlocked=['round-glasses','reading-chair'];s.equipment.chair=s.equipment.room='reading-chair';s.equipment.accessory='round-glasses';command(s,{type:'test-access',enabled:true,requestId:'old-trial'},0);s.testAccess.equipment.chair=s.testAccess.equipment.room='chair-sage';s.schema=4;delete s.positions;delete s.testAccess.positions;for(const e of [s.equipment,s.testAccess.equipment])for(const k of SLOTS.filter(k=>!LEGACY_SLOTS.includes(k)))delete e[k];return s;}
test('Actual schema4 bytes are backed up before8; original rewards,outfits,time and enabled test choice survive',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'owl-placement-upgrade-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const old=oldState(),bytes=Buffer.from(JSON.stringify(old,null,2)+'\n'),file=path.join(dir,'focus-state.json');fs.writeFileSync(file,bytes);const store=new FileStore(dir);try{const s=store.read();assert.equal(s.schema,9);assert.deepEqual(s.positions,{});assert.deepEqual(s.testAccess.positions,{});for(const k of ['totalFocusMs','creditedMinutes','collection','active','preferences'])assert.deepEqual(s[k],old[k]);assert(s.testAccess.enabled);assert.equal(s.testAccess.equipment.chair,'chair-sage');assert.equal(s.equipment.chair,'reading-chair');const b=fs.readdirSync(dir).find(n=>n.startsWith('focus-state.schema4-'));assert(fs.readFileSync(path.join(dir,b)).equals(bytes));assert.equal(JSON.parse(fs.readFileSync(file)).schema,9);}finally{store.close();}});
test('Migration backup conflict or write failure leaves original schema4 bytes recoverable',t=>{for(const fail of ['backup','write']){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'owl-placement-failure-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const bytes=Buffer.from(JSON.stringify(oldState())),file=path.join(dir,'focus-state.json');fs.writeFileSync(file,bytes);const st=new FileStore(dir);try{if(fail==='backup'){const h=crypto.createHash('sha256').update(bytes).digest('hex');fs.writeFileSync(path.join(dir,'focus-state.schema4-'+h+'.json'),'conflict');}else st.write=()=>{throw Error('synthetic full disk');};assert.throws(()=>st.read());assert(fs.readFileSync(file).equals(bytes));}finally{st.close();}}});
test('Unknown schema4 positions and corrupt current positions stop before empty replacement',()=>{assert.throws(()=>migrateState({...oldState(),positions:{}}),/未知位置/);for(const p of [null,{lamp:{x:Infinity,y:0}},{'bad/id':{x:1,y:1}}])assert.throws(()=>validateState({...initialState(),positions:p}));});
test('Room outfit plus positions saves once, duplicate is idempotent,normal/test states remain separate and reopen restores offsets',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'owl-placement-save-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));let svc=new FocusService(new FileStore(dir),{catalog,startWithAllItems:true,clock:()=>({wall:1000,mono:0})});const before=svc.snapshot(),c=room(before,{lamp:'lamp-linen',rug:'rug-cloud'},{'lamp-linen':{x:16,y:-16},'rug-cloud':{x:-20,y:0}});svc.dispatch(c);const saved=svc.snapshot();assert.equal(saved.revision,before.revision+1);svc.dispatch(c);assert.equal(svc.snapshot().revision,saved.revision);assert.deepEqual(saved.equipment,before.equipment);assert.deepEqual(saved.positions,{});assert.equal(saved.totalFocusMs,0);assert.deepEqual(saved.collection.owned,[]);svc.close();svc=new FocusService(new FileStore(dir),{catalog,clock:()=>({wall:9999999,mono:0})});assert.deepEqual(svc.snapshot().testAccess.positions,saved.testAccess.positions);assert.deepEqual(svc.snapshot().testAccess.equipment,saved.testAccess.equipment);svc.dispatch({type:'test-access',enabled:false,requestId:'off'});assert.deepEqual(svc.snapshot().positions,{});assert.deepEqual(svc.snapshot().equipment,before.equipment);svc.close();});
test('Late missing item, unrecoverable bounds, stale position or mode switch cannot partly save or grant ownership',()=>{const s=initialState();command(s,{type:'test-access',enabled:true,requestId:'on'},0);const original=structuredClone(s),missing=structuredClone(catalog);missing.items.find(i=>i.id==='foreground-plant-small').assetState='missing';assert.throws(()=>command(s,room(s,{lamp:'lamp-linen','foreground-plant':'foreground-plant-small'},{'lamp-linen':{x:16,y:0}}),0,undefined,missing),/素材/);assert.deepEqual(s,original);assert.throws(()=>command(s,room(s,{lamp:'lamp-linen'},{'lamp-linen':{x:32769,y:0}}),0,undefined,catalog),/位置无效/);assert.deepEqual(s,original);const c=room(s,{lamp:'lamp-linen'},{});s.testAccess.positions={'rug-cloud':{x:10,y:0}};assert.throws(()=>command(s,c,0,undefined,catalog),/其他入口/);const d=room(s,{lamp:'lamp-linen'},{});command(s,{type:'test-access',enabled:false,requestId:'off'},0);assert.throws(()=>command(s,d,0,undefined,catalog),/其他入口/);});
test('Tabletop selection survives cabinet/empty while invisible; returning table restores attached offsets',()=>{const s=initialState();command(s,{type:'test-access',enabled:true,requestId:'on'},0);command(s,room(s,{tabletop:'tabletop-teapot'},{}),0,undefined,catalog);const {bindings}=require('../ui/placement-rules.cjs');assert.equal(s.testAccess.equipment.tabletop,'tabletop-teapot');assert(!bindings(catalog,s.testAccess.equipment,{}).some(r=>r.category==='tabletop'));command(s,room(s,{'side-furniture':'side-table'},{'side-table':{x:-20,y:0},'side-table--tabletop-teapot':{x:5,y:0}},'attach'),0,undefined,catalog);const b=bindings(catalog,s.testAccess.equipment,s.testAccess.positions).find(i=>i.id==='tabletop-teapot');assert.equal(b.translation.x,-15);const stored=structuredClone(s.testAccess.positions);command(s,room(s,{'side-furniture':'low-bookcase'},stored,'cabinet'),0,undefined,catalog);assert.equal(s.testAccess.equipment.tabletop,'tabletop-teapot');assert(!bindings(catalog,s.testAccess.equipment,stored).some(r=>r.category==='tabletop'));command(s,{type:'equip',slot:'side-furniture',item:null,requestId:'remove'},0,undefined,catalog);assert.equal(s.testAccess.equipment.tabletop,'tabletop-teapot');assert.deepEqual(s.testAccess.positions,stored);command(s,{type:'equip',slot:'side-furniture',item:'side-table',requestId:'restore'},0,undefined,catalog);assert.equal(bindings(catalog,s.testAccess.equipment,stored).find(r=>r.category==='tabletop').translation.x,-15);});
test('Normal save still checks earned rights and new null thresholds never create rewards',()=>{const s=initialState();assert.throws(()=>command(s,room(s,{'wall-art':'wall-owl-mona'},{}),0,undefined,catalog),/没有解锁/);const before=structuredClone(s);assert.deepEqual(s,before);assert(!catalog.items.filter(i=>i.developmentPlaceholder).some(i=>i.unlockMinutes!==null));});
test('Old schema8 reopen rejects selected fully unrecoverable positions in normal and inactive trial rooms without replacing original bytes',t=>{
 const fixtures=[];
 const outside=initialState();outside.schema=8;outside.positions={stool:{x:1024,y:0}};fixtures.push(outside);
 const trial=initialState();command(trial,{type:'test-access',enabled:true,requestId:'trial'},0);command(trial,{type:'test-access',enabled:false,requestId:'off'},0);trial.testAccess.positions={stool:{x:0,y:1000}};trial.schema=8;fixtures.push(trial);
 for(const s of fixtures){
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'owl-placement-invalid-reopen-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
  const file=path.join(dir,'focus-state.json'),bytes=Buffer.from(JSON.stringify(s)+'\n');fs.writeFileSync(file,bytes);const store=new FileStore(dir);
  try{assert.throws(()=>store.read(),/超出可找回的摆放范围/);assert.deepEqual(fs.readFileSync(file),bytes);assert.deepEqual(fs.readdirSync(dir).filter(n=>n.endsWith('.json')),['focus-state.json']);}finally{store.close();}
 }
});
